#!/usr/bin/env node
import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=dirname(fileURLToPath(import.meta.url));const version=readFileSync(join(root,'VERSION'),'utf8').trim();
export const GITHUB_INSTALL_COMMAND='npm install --global github:kelvinalfaro/consulting-ops';
export function compareVersions(a,b){const x=a.replace(/^v/,'').split('.').map(Number),y=b.replace(/^v/,'').split('.').map(Number);for(let i=0;i<3;i++){if((x[i]||0)>(y[i]||0))return 1;if((x[i]||0)<(y[i]||0))return-1}return 0}
async function check(){try{const response=await fetch('https://api.github.com/repos/kelvinalfaro/consulting-ops/releases/latest',{headers:{'user-agent':'consulting-ops-update'}});if(!response.ok)throw new Error(String(response.status));const release=await response.json();return{status:compareVersions(release.tag_name,version)>0?'update-available':'up-to-date',local:version,remote:release.tag_name.replace(/^v/,''),url:release.html_url}}catch(error){return{status:'offline',local:version,error:error.message}}}
function tracked(){return execFileSync('git',['ls-files'],{cwd:root,encoding:'utf8'}).split(/\r?\n/).filter(Boolean)}
function apply(){if(!existsSync(join(root,'.git')))return{status:'reinstall-required',reason:'This copy was installed without Git metadata.',command:GITHUB_INSTALL_COMMAND};const dirty=execFileSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}).trim();if(dirty)throw new Error('Working tree has changes. Commit or stash them before updating.');const backup=join(root,'.updates','backup');rmSync(backup,{recursive:true,force:true});for(const file of tracked()){const source=join(root,file);if(existsSync(source)){const target=join(backup,file);mkdirSync(dirname(target),{recursive:true});cpSync(source,target,{recursive:true})}}writeFileSync(join(root,'.updates','backup-version'),version);const pull=spawnSync('git',['pull','--ff-only'],{cwd:root,stdio:'inherit'});if(pull.status!==0)throw new Error('git pull failed; backup retained');spawnSync('npm',['install'],{cwd:root,stdio:'inherit',shell:process.platform==='win32'});return{status:'updated',backup}}
function rollback(){const backup=join(root,'.updates','backup');if(!existsSync(backup))throw new Error('No updater backup exists');cpSync(backup,root,{recursive:true,force:true});return{status:'rolled-back',version:existsSync(join(root,'.updates','backup-version'))?readFileSync(join(root,'.updates','backup-version'),'utf8'):null}}
async function main(){const command=process.argv[2]||'check';const result=command==='check'?await check():command==='apply'?apply():command==='rollback'?rollback():null;if(!result)throw new Error('Usage: node update-system.mjs check|apply|rollback');console.log(JSON.stringify(result,null,2))}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch((error)=>{console.error(error.message);process.exit(1)});
